/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "auth.h"

bool_t
xdr_auth_token (XDR *xdrs, auth_token *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, ~0))
		 return FALSE;
	return TRUE;
}
