/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUTH_H_RPCGEN
#define _AUTH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *auth_token;

#define AUTH_PROG 223232323
#define AUTH_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REQUEST_AUTHORIZATION 1
extern  auth_token * request_authorization_1(char **, CLIENT *);
extern  auth_token * request_authorization_1_svc(char **, struct svc_req *);
#define REQUEST_ACCESS_TOKEN 2
extern  char ** request_access_token_1(char **, CLIENT *);
extern  char ** request_access_token_1_svc(char **, struct svc_req *);
extern int auth_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REQUEST_AUTHORIZATION 1
extern  auth_token * request_authorization_1();
extern  auth_token * request_authorization_1_svc();
#define REQUEST_ACCESS_TOKEN 2
extern  char ** request_access_token_1();
extern  char ** request_access_token_1_svc();
extern int auth_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_auth_token (XDR *, auth_token*);

#else /* K&R C */
extern bool_t xdr_auth_token ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AUTH_H_RPCGEN */
